/* eslint-disable @next/next/no-sync-scripts */
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<script type="module" src="https://unpkg.com/x-frame-bypass"></script>
			</head>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
